name = "Webcomic"
license = "MIT"
licenselink = "https://github.com/arsoward/webcomic-theme/blob/master/LICENSE"
description = "A simple Hugo theme for webcomics."
homepage = "http://example.com/"
tags = ['webcomic']
features = []
min_version = "0.41.0"

[author]
  name = "Abigail Rose Quijada"
  homepage = "gitlab.com/arsoward"